create tablespace MID_TERM
datafile 'MID_TERM' size 50M;

--drop tablespace practicaParcial;

CREATE PROFILE student LIMIT 
    IDLE_TIME 20;
    
--drop profile student;
    
CREATE USER USUARIO_3
	IDENTIFIED BY USUARIO_3
	DEFAULT TABLESPACE MID_TERM
    QUOTA 20M ON MID_TERM;

--drop user USUARIO_1 CASCADE;

GRANT DBA TO USUARIO_3;
GRANT CONNECT TO USUARIO_3; 
GRANT CREATE SESSION TO USUARIO_3;

CREATE USER USUARIO_2 
	IDENTIFIED BY USUARIO_2
	DEFAULT TABLESPACE quiz 
	PROFILE student;

GRANT CONNECT TO USUARIO_2; 
GRANT CREATE SESSION TO USUARIO_2;

--drop user USUARIO_2;

CREATE TABLESPACE segundoTaller
     DATAFILE 'segundoTaller' SIZE 2000M;

CREATE USER DBA_2
	IDENTIFIED BY DBA_2
	DEFAULT TABLESPACE segundoTaller
	QUOTA UNLIMITED ON segundoTaller;

GRANT DBA TO DBA_2;

GRANT CONNECT TO DBA_2; 
GRANT CREATE SESSION TO DBA_2;
